In [ ]:
#PROGRAM1 

In [1]:
import numpy as np


In [2]:
dic = {'Boys' : [72, 68, 70, 69, 74], 'Girls' : [63, 65, 69, 62, 61]}

In [5]:
res = [{key : value[i] for key, value in dic.items()}
       for i in range(5)
       ]

In [6]:
res




[{'Boys': 72, 'Girls': 63},
 {'Boys': 68, 'Girls': 65},
 {'Boys': 70, 'Girls': 69},
 {'Boys': 69, 'Girls': 62},
 {'Boys': 74, 'Girls': 61}]

program 2

In [ ]:
array = np.random.randint(5, size=(4,4))   #2D ARRAY

In [ ]:
array


array([[3, 0, 2, 2],
       [0, 4, 2, 4],
       [2, 0, 0, 4],
       [2, 3, 3, 3]])

In [ ]:
r1 = np.mean(array)   # MEAN

In [ ]:
r1


1.5

In [ ]:
r2 = np.std(array)    #STDANDARD DEVIATION
r2


1.3228756555322954

In [ ]:
r3 = np.var(array)     #VARIANCE
r3

1.75

B PART

In [ ]:
b = [56, 48, 22, 41, 78, 91, 24 ,46, 8, 33]

In [ ]:
indices = np.argsort(b)   #return sorting value's indices

In [ ]:
indices

array([8, 2, 6, 9, 3, 7, 1, 0, 4, 5])

C PART

In [ ]:
n = int(input("enter n"))
m = int(input("enter m"))

array1 = np.random.randint(5, size=(n,m))
array1

enter n3
enter m4


array([[3, 3, 0, 3],
       [2, 4, 1, 0],
       [3, 0, 0, 4]])

In [ ]:
array1.dtype


dtype('int64')

In [ ]:
array1.shape

(3, 4)

In [ ]:
array1.reshape(2,6)

array([[3, 3, 0, 3, 2, 4],
       [1, 0, 3, 0, 0, 4]])

part D


In [ ]:

k = [0,56, 0, 22, 41,0, 78, 91, 0 ,46, 8, np.nan]    #list not the array
k

[0, 56, 0, 22, 41, 0, 78, 91, 0, 46, 8, nan]

In [ ]:
ar=[(2,3,2,1)]
ar.dtype     #wrong way

AttributeError: ignored

In [ ]:
c=np.array([1,0,0,2,3,3])

In [ ]:

zero=np.where(c==0)[0]
zero

array([1, 2])

In [ ]:
np.all(c)

False

In [ ]:
nzin = np.nonzero(c)   #retrun index

In [ ]:
nzin

(array([0, 3, 4, 5]),)

In [ ]:
#zin = np.where(c== 0)[0]  #index
#zin =np.where(c==0)[0]
z=np.argwhere(c==0)
z

array([[1],
       [2]])

In [ ]:
nin = np.argwhere(np.isnan(c))

In [ ]:
nin

array([[9]])

In [ ]:
import pandas as pd


FINISH

In [ ]:
df = pd.read_csv('bestsellers.csv')

In [ ]:
df

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
df["Name"]

0                          10-Day Green Smoothie Cleanse
1                                      11/22/63: A Novel
2                12 Rules for Life: An Antidote to Chaos
3                                 1984 (Signet Classics)
4      5,000 Awesome Facts (About Everything!) (Natio...
                             ...                        
545         Wrecking Ball (Diary of a Wimpy Kid Book 14)
546    You Are a Badass: How to Stop Doubting Your Gr...
547    You Are a Badass: How to Stop Doubting Your Gr...
548    You Are a Badass: How to Stop Doubting Your Gr...
549    You Are a Badass: How to Stop Doubting Your Gr...
Name: Name, Length: 550, dtype: object

In [ ]:
df["User Rating"]

0      4.7
1      4.6
2      4.7
3      4.7
4      4.8
      ... 
545    4.9
546    4.7
547    4.7
548    4.7
549    4.7
Name: User Rating, Length: 550, dtype: float64

In [ ]:
df["Author"][:8]

0                    JJ Smith
1                Stephen King
2          Jordan B. Peterson
3               George Orwell
4    National Geographic Kids
5         George R. R. Martin
6         George R. R. Martin
7                 Amor Towles
Name: Author, dtype: object

In [ ]:
df["Genre"].unique()

array(['Non Fiction', 'Fiction'], dtype=object)

In [ ]:
df["Price"].mean()

13.1

In [ ]:
df.nlargest(3, "Price")

Name  \
69   Diagnostic and Statistical Manual of Mental Di...   
70   Diagnostic and Statistical Manual of Mental Di...   
473                       The Twilight Saga Collection   

                               Author  User Rating  Reviews  Price  Year  \
69   American Psychiatric Association          4.5     6679    105  2013   
70   American Psychiatric Association          4.5     6679    105  2014   
473                   Stephenie Meyer          4.7     3801     82  2009   

           Genre  
69   Non Fiction  
70   Non Fiction  
473      Fiction

In [ ]:
df2 = df[["Author", "User Rating"]]

In [ ]:
df2 

Author  User Rating
0                    JJ Smith          4.7
1                Stephen King          4.6
2          Jordan B. Peterson          4.7
3               George Orwell          4.7
4    National Geographic Kids          4.8
..                        ...          ...
545               Jeff Kinney          4.9
546               Jen Sincero          4.7
547               Jen Sincero          4.7
548               Jen Sincero          4.7
549               Jen Sincero          4.7

[550 rows x 2 columns]